### ISSUE TITLE
Charmap error

### ISSUE THREAD

**Issue by Sam-Dowling** [Lapin0t/py-swirld#2]
I have installed
- python 3.5
- Bokeh-0.12.3
- pySodium

running the command
`bokeh serve --show viz.py --args 5`

presents me with this error
`ERROR:'charmap' codec can't decode byte 0x9d in position 1315: character maps to <undefined>`

**Comment by Lapin0t** [comment]
Did https://github.com/Lapin0t/py-swirld/commit/55a7a034eadb60d145f4a06232f46329202dbd20 fix it? Looking at the error message, it's most likely that the utf-8 character "►" wasn't correctly decoded...

**Comment by Sam-Dowling** [comment]
I already tried adding in the encoding and still got the error, but removing the 'special' characters from the strings; fixed the problem.
