### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by rbarghou** [Lapin0t/py-swirld#4]
Hello, I was interested in working on this project, but noticed there wasn't a license on it.

**Comment by Lapin0t** [comment]
Yeah, i'm sorry, someone already made the remark a while ago and i forgot to put it there... So here it is,
i just put an apache 2. Note that some parts of the work appear to be protected by patents at least in the US so you should do whatever needs to be done to comply to the US patents law before using the code in the US.

**Comment by rbarghou** [comment]
Thanks for putting the license on it.  It would be awesome if you would consider a GPL license.

Do you have any reference to the patent?  I couldn't find a reference to it.

**Comment by Lapin0t** [comment]
Why would you argue for GPL? I usually put my work under GPL but this repo is quite small and i tought that other libs already did the same thing with permissive licenses (but after looking up it seems most have no license...), Do you know how GPL plays with patents (and how patents work at all)? (for reference, the patents are [here](http://www.swirlds.com/ip/), the license for the SDK can be seen [there](http://www.swirlds.com/download/) and a noticeable thing they disallow is to build an IAM system with it)...
